version: '3'

volumes:
  dados:

networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:9.6
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Volume dos Dados
      # PATH LOCAL:PATH NO CONTAINER
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco # Pertence só à rede 'banco'

  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configurando um proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web # pertence só à rede 'web'
    depends_on:
      - app # inicialização do 'frontend' depende da inicialização de 'app'

  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
  
  queue:
    image: redis:3.2
    networks:
      - fila
  
  worker:
    image: python:3.6
    volumes:
      # Workers
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - queue
